version: "3"

services:
    nginx:
        image: yansongda/docker-nginx
        volumes:
            - D:\workspace\sites:/etc/nginx/conf.d
            - D:\workspace\www:/www
        networks:
            - lnmp
        depends_on:
            - php
        expose:
            - "80"
        ports:
            - "80:80"
    php:
        image: yansongda/docker-php7-fpm
        volumes:
            - D:\workspace\www:/www
        networks:
            - lnmp
        depends_on:
            - mariadb
            - redis
            - memcached
        expose:
            - "9000"
    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: yansongda
        volumes:
            - D:\workspace\data\mariadb:/var/lib/mysql
        networks:
            - lnmp
        expose:
            - "3306"
        ports:
            - "3306:3306"
    redis:
        image: redis
        volumes:
            - D:\workspace\data\redis:/data
        networks:
            - lnmp
        expose:
            - "6379"
    memcached:
        image: memcached
        networks:
            - lnmp
        expose:
            - "11211"
    tools:
        image: yansongda/tools
        volumes:
            - D:\workspace\www:/www
        networks:
            - lnmp

networks:
    lnmp: